### 채팅방 입장
< {%
    // 현재 시간을 한국 시간대로 변환
    const now = new Date();
    const koreaTimeOffset = 9 * 60; // 한국은 UTC+9
    const koreaTimestamp = new Date(now.getTime() + koreaTimeOffset * 60000).toISOString();
    client.global.set("koreaTimestamp", koreaTimestamp);
%}

GET http://localhost:8080/api/v1/chat/enter
Content-Type: application/json

#적절한 ID 를 입력해주세요
{
  "chatroomInfoId": "663fa5af10fa866c4c0232d7",
  "receiverNo": 2,
  "requestTime": "{{koreaTimestamp}}"
}

### 채팅방 조회 및 최신메시지 조회

GET http://localhost:8080/api/v1/chat/all
Content-Type: application/json

{
  "senderNo": 1,
  "receiverNo": 2
}