spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: Eighteen_BE

  profiles:
    include: sms, jwt, symmetric
    active: test

  kafka:
    bootstrap-servers: 0.0.0.0:39092
server:
  port: 8080

#logging:
#  level:
#    org:
#      springframework: TRACE


