spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: Eighteen_BE
  kafka:
    bootstrap-servers: 0.0.0.0:39092
server:
  port: 8080