### 로그인 편의
### 로그인
POST {{url}}/v1/api/user/sign-in?phoneNumber=01000000001
Content-Type: application/json

> {%
    const authHeader = response.headers.valueOf("Authorization").split("Bearer-")[1]
    // local token 에 세팅
    client.global.set("token", authHeader);
%}

### 토너먼트 강제 시작
POST {{url}}/v1/api/tournament/force-start

### 토너먼트 강제 종료
POST {{url}}/v1/api/tournament/force-end

### 토너먼트 검색
GET {{url}}/v1/api/tournament/search
Content-Type: application/json

### 토너먼트 투표
POST {{url}}/v1/api/tournament/final/vote
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tournamentNo": 12,
    "participantIdsOrderByRank": [
        "tester22",
        "tester21",
        "tester20"
    ]
}

### 토너먼트 결과 조회
GET {{url}}/v1/api/tournament/final/result?tournamentNo=6
Content-Type: application/json
Authorization: Bearer {{token}}

### 토너먼트 32인 강제 레디스에 올리기
PUT {{url}}/v1/api/tournament/force-pick-most-liked-user-to-redis

### (편의) 토너먼트 모두 조회
GET {{url}}/v1/api/tournament/all
Content-Type: application/json
Authorization: Bearer {{token}}
