### 토너먼트 강제 시작
POST {{url}}/v1/api/tournament/force-start

### 토너먼트 강제 종료
POST {{url}}/v1/api/tournament/force-end

### 토너먼트 검색
GET {{url}}/v1/api/tournament/search?size=10&page=0&sort=TOURNAMENT_NO&sortDirection=DESC
Content-Type: application/json

### 토너먼트 투표
POST {{url}}/v1/api/tournament/final/vote
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "voterId": "voter1",
  "tournamentNo": 16,
  "participantIdsOrderByRank": [
    "user1",
    "user2",
    "user3"
  ]
}

### 토너먼트 결과 조회
GET {{url}}/v1/api/tournament/final/result?tournamentNo=16

### 토너먼트 32인 강제 레디스에 올리기
PUT {{url}}/v1/api/tournament/force-pick-random-user-to-redis
