name: Dockerisze on Dev Branch

on:
  push:
    branches:
      - dev # workflows work on pushing to dev!
  pull_request_target:
    branches:
      - dev # workflows work when pr **merge** request to dev

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Check out the current repository!

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          content: . # docker image build context path
          file: ./Dockerfile # dockerFile location in repository!
          push: true # push image to docker registry  - https://kimjingo.tistory.com/79
          tags: eighteen_be/eighteen:0.0.1 # must change version when app updated  - psj