name: test-before-pr

on:
  pull_request:
    branches: [ main, dev, feat/test-before-pr ]

jobs:
  test-before-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Copy private resources
        run: |
          ./gradlew copyYaml --no-daemon
          ./gradlew copyEnv --no-daemon

      - name: Docker compose up
        run: docker-compose --env-file .env.local up -d

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Docker compose down
        run: docker-compose down -v